### ISSUE TITLE
Timeout fetching OpenSprinkler resource status data

### ISSUE THREAD

**Issue by pixel8383** [vinteo/hass-opensprinkler#145]
I am using this integration in order to control an OpenSprinkler station. The station is running fine on firmware 2.1.9 (7) but sometimes my HA installation records this error on the logger.

I am running Home Assistant 2021.1.5

```
Logger: custom_components.opensprinkler
Source: helpers/update_coordinator.py:148
Integration: OpenSprinkler (documentation)
First occurred: 01:23:44 (31 occurrences)
Last logged: 15:15:30
Timeout fetching OpenSprinkler resource status data 
```

I guess I can ignore it but it would be nice to understand how to stop it from happening.

Thanks you.

**Comment by torrancew** [comment]
I'm seeing similar log messages, and have also noticed that after a period of time, HA reports the OpenSprinkler-populated sensors & switches with a **state** of `Unavailable` -- the entities are not marked as such, but switches are no longer interactive and sensors only report this string.

**Comment by travisghansen** [comment]
Can you actually reach the controller UI with a browser? I've seen similar issues where I ultimately found out it was due to a weak wifi signal. My controller would eventually drop and never come back until I rebooted it (I ended up installing a smart switch to automate that). I have since put an AP much closer to my controller and the reliability of the controller (and this plugin) have increased dramatically.

**Comment by torrancew** [comment]
First, a caveat:
My OpenSprinkler install is only a couple of weeks old, and in that time I've only observed this issue 2 times.

With the above in mind, both times I have noticed this issue, I have been able to reach the web UI of the controller itself with no issues. I have never once needed to power cycle or otherwise take action on the controller itself -- but the HA integration remains in this inconsistent state until/unless I `reload` the integratoin -- at which point everything starts reporting once more in HA.

It could be that the controller is losing signal intermittently -- but if the controller itself ultimately recovers from this conditoin, ideally the HA integration can, as well.

**Comment by vinteo** [comment]
Hi guys,

Unfortunately I don't think it is possible to get rid of the log messages entirely. Even with the best network connections sometimes the OS controller takes longer than expected to respond. Of course the better the network connection, the less the log messages will appear. 

However having said that, this message can be ignored most of the time as the next update will go ahead (subject to network). So as long as you have a decent network connection to the OS controller, the integration should be able to recover gracefully from it. Not sure about a prolonged network disruption though.

For my own instance I get the message maybe 1 per day or two but I have it running for weeks at a time (never ran it longer cause I always have to tweak my HA config and reboot lol) without having to need to touch the integration, HA or the OS controller.

**Comment by torrancew** [comment]
For what it's worth, it's been a week since I've had any issues with this integration. Will keep an eye on things in case it resurfaces.

**Comment by vinteo** [comment]
Great, I will close this for now
