### ISSUE TITLE
Does not work on 2012.12.03

### ISSUE THREAD

**Issue by JurajNyiri** [vinteo/hass-opensprinkler#202]
```
Unable to install package pyopensprinkler==0.7.5: ERROR: Cannot install pyopensprinkler==0.7.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip
```

Probably related to https://github.com/home-assistant/core/pull/83795 .

**Comment by RobHomey** [comment]
Looks like the same error as previous HA update. After 2022.12.3 update I get the following error:

Logger: homeassistant.util.package
Source: util/package.py:98 
First occurred: 10:26:51 (3 occurrences) 
Last logged: 10:27:18

Unable to install package pyopensprinkler==0.7.5: ERROR: Cannot install pyopensprinkler==0.7.5 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip available: 22.3 -> 22.3.1 [notice] To update, run: pip install --upgrade pip

**Comment by vinteo** [comment]
For now a downgrade to 1.1.12 should fix it I think

**Comment by RobHomey** [comment]
After installing V1.1.14 Opensprinkler works again. Op 12 dec. 2022 om 12:36 heeft Vincent Teo ***@***.***> het volgende geschreven:﻿
try v1.1.14

**Comment by JurajNyiri** [comment]
I confirm the fix works. Thank you!
