### ISSUE TITLE
OpenSprinkler broken after upgrading to 2023.7.3

### ISSUE THREAD

**Issue by CZonin** [vinteo/hass-opensprinkler#228]
Just updated from 2023.7.2 to 2023.7.3 and getting the following error at startup:

```
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 4:17:01 PM (3 occurrences)
Last logged: 4:17:08 PM

Unable to install package pyopensprinkler==0.7.6: ERROR: Cannot install pyopensprinkler==0.7.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2 [notice] To update, run: pip install --upgrade pip
```

**Comment by larry-glz** [comment]
I concur - same failure on 2 different HA installations upgraded to 2023.7.3:

`Unable to install package pyopensprinkler==0.7.6: ERROR: Cannot install pyopensprinkler==0.7.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2 [notice] To update, run: pip install --upgrade pip`

**Comment by collinstork** [comment]
caused by this: https://github.com/vinteo/py-opensprinkler/issues/77

**Comment by vinteo** [comment]
Please try version 1.1.17

**Comment by CZonin** [comment]
Version 1.1.17 works. Thanks for the quick fix!

**Comment by larry-glz** [comment]
up and running again w/ 2023.7.3 and 1.1.17.  thanks for the quick turnaround!
