### ISSUE TITLE
Issue upgrading to Home Assistant Core 2023.8.0

### ISSUE THREAD

**Issue by deanjunk** [vinteo/hass-opensprinkler#238]
Logger: homeassistant.setup
Source: setup.py:209
First occurred: 12:03:32 PM (1 occurrences)
Last logged: 12:03:32 PM

Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.6'].

**Comment by vinteo** [comment]
Are you on version 1.1.17?

**Comment by deanjunk** [comment]
No, v1.1.15 which is the latest version available through HACS.

**Comment by vinteo** [comment]
It should be v1.1.17. did you update HACS as well? Not sure why yours is
still at 1.1.15

**Comment by deanjunk** [comment]
Everything (except Home Assistant Core) is updated and the latest version is v1.1.15...

**Comment by vinteo** [comment]
The only way to fix your issue is to upgrade so you might need to upgrade
manually. There are instructions in the README

**Comment by luebbe** [comment]
Same here. First after upgrading to HASS 2023.8.0 I was also confronted with the "requirements not found" error message.
One or two HACS versions later, these errors disappeared, but the OpenSprinkler integration still doesn't work. Everything is flagged as unavailable.

Today I updated to HASS 2023.8.4 and the error message upon startup is (repeated multiple times)

> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: custom_components.opensprinkler
> Source: helpers/update_coordinator.py:262
> Integration: OpenSprinkler (documentation, issues)
> First occurred: 15:23:00 (6 occurrences)
> Last logged: 15:26:32
> 
> Error fetching OpenSprinkler resource status data: Error fetching OpenSprinkler state

OpenSprinkler is installed via HACS and I am on version 1.1.17 since a while.
I can connect to open sprinkler without any problems using the app or a web browser.

How can I get the open sprinkler integration up and running again?

**Comment by EdLeckert** [comment]
Today I installed a clean copy of Home Assistant 2023.8.4, HACS, and OpenSprinkler 1.1.17 (via HACS) on a clean VM. It works fine.

The only way I've been able to re-create your exact error is to go into .storage and corrupt the password. Then I get your error, but I also get:

```
Logger: homeassistant.config_entries
Source: config_entries.py:430
First occurred: 3:34:32 PM (1 occurrences)
Last logged: 3:34:32 PM

Config entry 'OpenSprinkler' for opensprinkler integration not ready yet: None; Retrying in background
```
Do you see any other errors besides the one you mentioned?

Have you tried deleting and re-creating the OpenSprinkler integration, carefully checking the URL and password? If so, does the Success dialog appear with the option to choose an Area for the device?

**Comment by luebbe** [comment]
Deleting and re-adding the integration did the trick. I don't know what went wrong between the HASS upgrades. Thanks for your help.
