### ISSUE TITLE
1.2.0 Update rendered implementation unusable

### ISSUE THREAD

**Issue by theOrakleAtBurns** [vinteo/hass-opensprinkler#248]
I love the innovation and the additions, but I have 40 station and 10 programs...

I'll let you do the math, but this created more entries than Hass could handle with your current threading.

**Comment by EdLeckert** [comment]
Well, that's an impressive system you have there.

Were you able to roll back to the previous version while we figure this out?

Also, may I ask what features of the integration you mostly use?

**Comment by EdLeckert** [comment]
Sorry you had to deal with that. I've had HA upgrades blow up my system and it's no fun.

May I ask what you're using for your HA server?

Also, can you tell me a bit more about your experience with the update...briefly, what worked and what didn't?

**Comment by theOrakle** [comment]
No prob at all man - so hass runs on a ESX cluster of NUCs  (i7,32 GB) connected to an all flash synology array via 10 G iSCSI.  The db is Postgres on another VM on the same cluster. Each node has 2 core & 8GB.

On the upgrade front:
 - it was the only custom component that was ungraded
 -  Watched the logs after restart & it complained that a value needed to be 0-23
 - navigated to the integration via hass just fine
 - One I clicked on the device, it couldn’t render the 630 entities in under 2 minutes and scrolling was not responsive on Safari, Chrome or companion app

**Comment by theOrakle** [comment]
Note - I have more entities on other integrations with more devices.   


![IMG_3015](https://github.com/vinteo/hass-opensprinkler/assets/37029980/701df286-fe40-4624-ba7c-577b0f4ea2f1)

**Comment by theOrakle** [comment]
Forgot to add… ran top on both hass and the db while I was waiting for the integration to render one of the times and no I/o or cpu wait

**Comment by theOrakle** [comment]
I have another environment (yellow with a gGb/s NvME), that I can use if you want me to test something for you

**Comment by theOrakle** [comment]
You are correct sir.

**Comment by EdLeckert** [comment]
OK, I set up an environment to simulate your system as best as I can with only 8 stations and 1 program in my one controller. I modified the integration to create entities for 10 copies of the one program and 5 copies of the 8 stations, for a total matching your system. This resulted in the creation of 630 entities for the 1 device in the integration. I'm running VirtualBox on a laptop, Chrome on same laptop, wired connection to my OS controller. Far from an ideal comparison, but gives me an idea of the impact.

What I observed when using V 1.1.17 was that the device page loaded in under a second. Using V 1.2.1 it takes about 4 seconds. There is no interaction with the OS controller due to the page load (I reduced the frequency of polling from 5 seconds to 5 minutes for the test, and there was no traffic.) The page is simply loading from the HA entities.

So I'm not sure what was causing your browsers to hang. Perhaps some entities did not have a valid state yet? Maybe the 5 second poll interval is too fast for a system of your size with the added entities?

If you still want to test some ideas and can afford to create and destroy installations easily, there are a couple of things you could try using the latest release on your test system. _**It will still create the 630 entities if you don't comment out the lines below, so be warned.**_

Of the 630 entities, 400 are the station durations, one for each station for each program. If you go to `opensprinkler/number.py` you can comment out the following lines with a leading "#" and they won't get created. Then start HA and configure the integration. Mine took about 1 second to load the device page after this change.

```
    for _, program in controller.programs.items():
        for _, station in controller.stations.items():
            entities.append(
                ProgramDurationNumber(entry, name, program, station, coordinator)
            )

```

If you make this change after the entities are already created, they won't get deleted, but they won't be loaded into the device page. 

If all goes well, you could try uncommenting the lines and reducing the polling interval. In `opensprinkler/const.py` change `DEFAULT_SCAN_INTERVAL` to something like 30 and restart HA.

If you have trouble with the device page at any point, you could check `Developer tools\STATES` and see if the entities look reasonable.

Oh, and I would definitely disable your production integration while doing this, so only one instance is hitting your OS controller at a time.

Finally, as to your Z-Wave example above: 1373 entities spread over 78 devices is an average of fewer than 18 entities per device, so you wouldn't be loading many entities on each device page.

Let me know if you have any questions or if you're not able to do this. Thanks!

**Comment by theOrakle** [comment]
I'll try all of this over the weekend...  

For now, I disabled new entities... and all is good.
<img width="606" alt="image" src="https://github.com/vinteo/hass-opensprinkler/assets/37029980/800e9379-a9c2-49ef-9251-2e92eaf648d0">

I'm also seeing the following periodically:
```
2023-09-22 23:39:27.101 INFO (MainThread) [backoff] Backing off _request_http(...) for 0.1s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
2023-09-22 23:39:32.127 INFO (MainThread) [backoff] Backing off _request_http(...) for 0.6s (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
```

It honestly feels like I am overrunning my OS 3... It's on a wired network 1 Gb (the NIC only supports 10/100)
<img width="201" alt="image" src="https://github.com/vinteo/hass-opensprinkler/assets/37029980/6289cf10-06e1-4d9f-b7ea-41f098df0cd8">
<img width="1014" alt="image" src="https://github.com/vinteo/hass-opensprinkler/assets/37029980/9c03a63d-cf5b-4ef7-97e4-304cdccd8ad1">

<img width="627" alt="image" src="https://github.com/vinteo/hass-opensprinkler/assets/37029980/667103c7-b328-4766-8793-0c66321ddd99">


I know that my setup is much larger than anyone else's, so don't burn midnight oil on it.  I originally open this to make sure you did the math of what that did at scale, but this looks like another fine tuning exercise for my ridiculous hobby.

<img width="476" alt="image" src="https://github.com/vinteo/hass-opensprinkler/assets/37029980/0fba246b-6c71-499b-a2e0-2f7a3fed92a8">

**Comment by theOrakle** [comment]
You nailed it...

"Oh, and I would definitely disable your production integration while doing this, so only one instance is hitting your OS controller at a time."

After the update, OS 3 hardware cannot keep up with the requests from 2 hass systems.

**Comment by EdLeckert** [comment]
I suspect you're going to find that _one_ instance polling every 5 seconds is too much for a system your size. But that's easily fixed.

**Comment by EdLeckert** [comment]
> * Watched the logs after restart & it complained that a value needed to be 0-23

See #254.
