### ISSUE TITLE
OpenSprinkler not working since update to HA2023.10.2

### ISSUE THREAD

**Issue by wokkeltje13** [vinteo/hass-opensprinkler#259]
I receive the following errors:
Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.7'].

Unable to install package pyopensprinkler==0.7.7: ERROR: Cannot install pyopensprinkler==0.7.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by CZonin** [comment]
Just ran into this as well

**Comment by shaggee** [comment]
Same here

Setup failed for custom integration opensprinkler: Requirements for opensprinkler not found: ['pyopensprinkler==0.7.7'].
+
Unable to install package pyopensprinkler==0.7.7: ERROR: Cannot install pyopensprinkler==0.7.7 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by mkmer** [comment]
@vinteo : HA bumped aiohttp3.8.6 - we need the API to either == 3.8.6 or > 3.8.5 the requirement for aiohttp.

**Comment by vinteo** [comment]
update to v1.2.3

**Comment by CZonin** [comment]
> update to v1.2.3

All good with 1.2.3. Thanks for the quick update!
