### ISSUE TITLE
*_program_running sensor not working as expected

### ISSUE THREAD

**Issue by paranerd** [vinteo/hass-opensprinkler#312]
The `*_program_running` binary sensor only switches to "on" when the program has been started automatically (on schedule). However when I start it manually ("ad hoc") it stays "off".

I would expect the sensor to turn to "on" in either case because the program is running no matter the cause.

Anyway, thanks for the great work :-)!

**Comment by EdLeckert** [comment]
When a program is started manually, the program index is sent to the controller so that it can run the correct program. However, when the controller is then queried, it reports that the Run-once program is running, and not the program that was actually started. It returns program index 254 in the ps (Program status data) parameter of the controller variables, as seen in this example, where the program calls for Zone 5 (Drip) to run for 10 minutes:

`'ps': [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [254, 599, 1727787196, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],`

This can also be observed in the status line at the bottom of the OpenSprinker web app:

![OpenSprinker status line](https://github.com/user-attachments/assets/6df56379-1523-45b3-a728-01c4343c20d6)

This is also the case if the program is manually started from the OpenSprinkler web app.

Therefore, the program that was manually started will always report a state of "off" in Home Assistant.

You could of course log a bug with the OpenSprinkler firmware project.

**Comment by paranerd** [comment]
Thanks for the deep dive, really appreciate it!

For anyone looking for a workaround, I'm using the following as my value template:

```
{{ states('sensor.s08_station_status') in ['waiting', 'once_program', 'program'] }}
```

This simply checks the status of the very last of my stations (8).

Based on my debugging, the state sets as follows:

- 'idle' when off
- 'manual' when turned on individually
- 'waiting' when scheduled to be running in a program
- 'once_program' when running in the ad-hoc program
- 'program' when running in an automated program

It's a little hacky, of course, but from what I can tell it does the job.
