### ISSUE TITLE
HA 0.110.0bX not working with hass-opensprinkler

### ISSUE THREAD

**Issue by cogneato** [vinteo/hass-opensprinkler#51]
Testing the current beta 0.110.0b0 (currently 0b3) and opensprinkler integration is not working.
Last working version was 109.6

I see you've got a PR for an official HA integration and it's gotten some attention! Really looking forward to it!

## System Information
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
hassio | true
host_os | HassOS 4.6
installation_type | Home Assistant
os_name | Linux
os_version | 5.4.39
python_version | 3.7.7
supervisor | 222
timezone | America/Denver
version | 0.110.0b3
virtualenv | false

## Traceback
```
'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 453, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 484, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 622, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_opensprinkler/switch.py", line 89, in turn_on
    self._station.turn_on(int(float(mins.state)))
AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by vinteo** [comment]
Sorry for the late reply, I just upgraded to 0.110.2 and it works for me. Did you recently add a `input_number` entity? Please take a look at the troubleshooting section of the README

**Comment by travisghansen** [comment]
@cogneato we're interested in knowing what features you're hoping to get out of the new integration. We're debating about what to make sensors, switches, attributes, services, etc, etc. If you have any input/expectations please shout them out.

**Comment by docsparks** [comment]
> @cogneato we're interested in knowing what features you're hoping to get out of the new integration. We're debating about what to make sensors, switches, attributes, services, etc, etc. If you have any input/expectations please shout them out.

Im semi-new to homeassistant and think this can be done by grouping and a bunch of extra work, but a easy way to create a 'virtual zone' within the integration that would allow you to group a few zones as a 'masterzone' so in an scenario:

i have 3 zones and the first half of the day I feed all three zones (sequentially) from tap water, where the second half of the day i feed all three zones (sequentially) with fertilizer.   some days I feed all three zones with organic teas.

because zone 1, 2, 3 all rely on a masterzone, which pump and which valve that is being fed into the manifold changes by hour of the day and by day of the week. 

So to make a group such as 
master1)  clean water pump and valve after pump
master2) fertilzier water pump and valve after pump
master3) organtic tea water pump and valve after pump

so when i decide to manually water one zone by random, i have to turn 2 separate valves on via app and then turn on the zone for a similar time frame.    making a premade program via the opensprinkler app for each of these scenarios and watering durations would be next to impossible.   

a tap of the screen in hassio to decide zone and which feed source, and time, and press start.
this is my ideal way to handle this, and simplifying the process without hardcoding would be awesome.

also, a different way to run a 'custom program from hassio' would also be awesome.  the current use scenario within OpenSprinkler is that you can only configure programs to run in the order in which the wires and valves and hardwired, and to run a custom program , out of order from the hardwiring, would also be a amazing and sought after feature by many.

im currently trying to datalog which zone or program ran and when, and keep track of flow via espeasy and hall flowmeter.  saving to sql or csv file,  any nudge in the right direction would be greatly appreciated.   keep up the good work!

**Comment by travisghansen** [comment]
Wow, so you’re interested in replacing the program logic in OpenSprinkler with hass? In that case OpenSprinkler literally just becomes a bunch of relays for you..

@vinteo might be good to add a service that would handle turning off all stations.

**Comment by travisghansen** [comment]
@docsparks I think we’re probably really close to supporting much of the scenarios you described above. We’re getting ready to snap 1.0 but 1.1 will support one off programs which would likely be helpful for you in some shape or form. I’m interested in knowing what we’re missing to support any of the other things you’ve mentioned.

**Comment by vinteo** [comment]
@cogneato wondering if you still have issues with the new versions? Closing this, please open a new issue if still having issues with the new version
